import type { ServiceRequest, VerificationCheck, ExtractedField } from "./types"

export const governmentRequests: ServiceRequest[] = [
  {
    id: "REQ-2041",
    citizen: "Aarav Sharma",
    service: "Birth Certificate",
    department: "Civil Registration",
    documentType: "Aadhaar",
    submittedAt: "2026-08-18T09:12:00",
    status: "employee-review",
    aiConfidence: 94,
    verification: "verified",
    assignedTo: "M. Nair",
    citizenAction: "none",
  },
  {
    id: "REQ-2040",
    citizen: "Priya Menon",
    service: "Income Certificate",
    department: "Revenue",
    documentType: "Aadhaar + Payslip",
    submittedAt: "2026-08-18T08:45:00",
    status: "ai-verified",
    aiConfidence: 71,
    verification: "warning",
    assignedTo: "Unassigned",
    citizenAction: "none",
  },
  {
    id: "REQ-2039",
    citizen: "Rahul Verma",
    service: "Property Mutation",
    department: "Revenue",
    documentType: "Sale Deed",
    submittedAt: "2026-08-18T08:02:00",
    status: "approved",
    aiConfidence: 88,
    verification: "verified",
    assignedTo: "S. Iyer",
    citizenAction: "notified",
  },
  {
    id: "REQ-2038",
    citizen: "Fatima Khan",
    service: "Caste Certificate",
    department: "Social Welfare",
    documentType: "Aadhaar",
    submittedAt: "2026-08-17T16:30:00",
    status: "rejected",
    aiConfidence: 42,
    verification: "failed",
    assignedTo: "M. Nair",
    citizenAction: "correction-requested",
  },
  {
    id: "REQ-2037",
    citizen: "Daniel George",
    service: "Marriage Registration",
    department: "Civil Registration",
    documentType: "Aadhaar x2",
    submittedAt: "2026-08-17T14:10:00",
    status: "submitted",
    aiConfidence: 0,
    verification: "pending",
    assignedTo: "Unassigned",
    citizenAction: "none",
  },
  {
    id: "REQ-2036",
    citizen: "Sneha Reddy",
    service: "Domicile Certificate",
    department: "Revenue",
    documentType: "Aadhaar + Utility Bill",
    submittedAt: "2026-08-17T11:55:00",
    status: "employee-review",
    aiConfidence: 83,
    verification: "warning",
    assignedTo: "S. Iyer",
    citizenAction: "none",
  },
  {
    id: "REQ-2035",
    citizen: "Vikram Singh",
    service: "Birth Certificate",
    department: "Civil Registration",
    documentType: "Aadhaar",
    submittedAt: "2026-08-17T10:20:00",
    status: "approved",
    aiConfidence: 96,
    verification: "verified",
    assignedTo: "M. Nair",
    citizenAction: "notified",
  },
]

export const businessRequests: ServiceRequest[] = [
  {
    id: "INV-8842",
    citizen: "Acme Logistics Pvt Ltd",
    service: "Invoice Onboarding",
    department: "Accounts Payable",
    documentType: "Tax Invoice",
    submittedAt: "2026-08-18T09:30:00",
    status: "employee-review",
    aiConfidence: 91,
    verification: "verified",
    assignedTo: "R. Kapoor",
    citizenAction: "none",
  },
  {
    id: "INV-8841",
    citizen: "Northwind Supplies",
    service: "Vendor KYC",
    department: "Procurement",
    documentType: "GST + PAN",
    submittedAt: "2026-08-18T08:50:00",
    status: "ai-verified",
    aiConfidence: 68,
    verification: "warning",
    assignedTo: "Unassigned",
    citizenAction: "none",
  },
  {
    id: "INV-8840",
    citizen: "Meridian Contractors",
    service: "Contract Intake",
    department: "Legal",
    documentType: "MSA Agreement",
    submittedAt: "2026-08-18T08:05:00",
    status: "approved",
    aiConfidence: 89,
    verification: "verified",
    assignedTo: "L. Fernandes",
    citizenAction: "notified",
  },
  {
    id: "INV-8839",
    citizen: "Blue Ocean Traders",
    service: "Expense Reimbursement",
    department: "Finance",
    documentType: "Receipts",
    submittedAt: "2026-08-17T17:12:00",
    status: "rejected",
    aiConfidence: 38,
    verification: "failed",
    assignedTo: "R. Kapoor",
    citizenAction: "correction-requested",
  },
  {
    id: "INV-8838",
    citizen: "Pioneer Textiles",
    service: "Vendor KYC",
    department: "Procurement",
    documentType: "GST + PAN",
    submittedAt: "2026-08-17T15:40:00",
    status: "submitted",
    aiConfidence: 0,
    verification: "pending",
    assignedTo: "Unassigned",
    citizenAction: "none",
  },
]

export const birthCertificateFields: ExtractedField[] = [
  { key: "name", label: "Child's Full Name", value: "Aarav Sharma", source: "ai", confidence: 97 },
  { key: "dob", label: "Date of Birth", value: "2026-02-14", source: "ai", confidence: 95 },
  { key: "gender", label: "Gender", value: "Male", source: "ai", confidence: 92 },
  { key: "father", label: "Father's Name", value: "Rohan Sharma", source: "ai", confidence: 94 },
  { key: "mother", label: "Mother's Name", value: "Anjali Sharma", source: "ai", confidence: 93 },
  { key: "address", label: "Residential Address", value: "12 MG Road, Bengaluru, KA 560001", source: "ai", confidence: 81 },
  { key: "age", label: "Age (derived)", value: "6 months", source: "derived" },
  { key: "hospital", label: "Place of Birth", value: "", source: "missing" },
  { key: "contact", label: "Contact Number", value: "+91 98450 12345", source: "manual" },
]

export const verificationChecks: VerificationCheck[] = [
  {
    id: "identity",
    label: "Identity Verification",
    description: "Aadhaar photo & demographic match against submitted details.",
    state: "verified",
    confidence: 96,
  },
  {
    id: "completeness",
    label: "Document Completeness",
    description: "All required pages present and legible.",
    state: "verified",
    confidence: 92,
  },
  {
    id: "consistency",
    label: "Information Consistency",
    description: "Cross-field checks between document and form data.",
    state: "warning",
    confidence: 74,
  },
  {
    id: "required",
    label: "Required Fields",
    description: "Place of Birth is missing from the submission.",
    state: "warning",
    confidence: 68,
  },
  {
    id: "compliance",
    label: "Rules & Compliance",
    description: "Eligibility rules for Civil Registration satisfied.",
    state: "verified",
    confidence: 90,
  },
  {
    id: "exceptions",
    label: "Exceptions & Mismatches",
    description: "No duplicate registration detected in registry.",
    state: "verified",
    confidence: 88,
  },
]

export const recentActivity = [
  { id: "a1", actor: "AI Engine", action: "Verified REQ-2035 with 96% confidence", time: "2 min ago", type: "ai" as const },
  { id: "a2", actor: "M. Nair", action: "Approved REQ-2035 (Birth Certificate)", time: "6 min ago", type: "approve" as const },
  { id: "a3", actor: "System", action: "Notified citizen for REQ-2039", time: "14 min ago", type: "notify" as const },
  { id: "a4", actor: "S. Iyer", action: "Requested correction on REQ-2038", time: "22 min ago", type: "reject" as const },
  { id: "a5", actor: "Citizen", action: "Submitted REQ-2041 via QR (Civil Registration)", time: "38 min ago", type: "submit" as const },
]

export const departmentBreakdown = [
  { name: "Civil Registration", total: 412, approved: 356 },
  { name: "Revenue", total: 298, approved: 241 },
  { name: "Social Welfare", total: 187, approved: 142 },
  { name: "Transport", total: 143, approved: 118 },
]
